README.md, agent/config.yaml, docker-compose.yml, grafana/definitions/mlt.json, prometheus/prometheus.yml, source/mythical-beasts-requester/index.js, source/mythical-beasts-server/index.js, tempo/tempo.yaml
This also cleans some of the code up, and fixes an issue with
table dropping/recreation every 24 hours.
Signed-off-by: Heds Simons <hedley.simons@grafana.com>
=> Moves from Grafana Agent metrics to Tempo server-side metrics.

docker-compose.yml
This PR sets 3 env vars that removes the login screen when running the local demo. It also sets the anonymous user to be an admin so they can have access to everything inside of their locally running instance.
=> Remove login form from local docker-compose

docker-compose-otel.yml, docker-compose.yml, grafana/definitions/mlt-erroring-endpoints.json
This PR adds a new dashboard designed to show off Tempo structrural operators. It is a simple dashboard that let's you choose an endpoint and it shows downstream errors using a query like:
```
{ span.http.target = "/failing/endpoint" } >> { status = error }
```
Tempo was also fast forwarded to 2.2-rc.0 since this is the first release supporting structural operators.
=> Adds an "erroring endpoints" dashboard

grafana/definitions/mlt.json
Updates the `95th Percentile Response Latencies (ms)` Panel to use `$__rate_interval` instead of a hardcoded value of 15s.
=> Specify `$__rate_interval` in mlt.json

agent/config.yaml
Ensures we now use a pre-defined metrics instance for remote_write
and includes a configuration example for error-based tail sampling.
=> Update static Agent config with corrections.

docker-compose-cloud-unconfigured.yml, docker-compose-otel.yml, docker-compose.yml, grafana/definitions/mlt.json
This uses the `main` branch of Grafana for the moment, but it's worth unpinning to get the functionality of Tempo dashboard variables!
=> Moves from metrics label dashboard variables to trace attribute variables.

grafana/definitions/mlt.json
Readd Dashboard Tags to mlt.json, so Dashboard Links work as expected again.
=> Readd Dashboard Tags to mlt.json

docker-compose-cloud-unconfigured.yml, docker-compose-otel.yml, docker-compose.yml, grafana/definitions/mlt.json, tempo/tempo.yaml
These are the changes that were necessary to activate the UI for metricsSummary toggle in Grafana. Changes are to docker-compose and tempo yaml files. Many thanks to @mdisibio for help troubleshooting and coming up with the fix.
I didn't do a pull before creating this PR. One thing we had to do was change the Grafana image from main to an earlier version (in this case, the one that was listed in the PR for adding metricsSummary toggle). At the time, the main grafana image was not running queries when the metricsSummary toggle was enabled.
=> Updates for adding metrics-summary toggle

README.md, agent/config.river, otel/otel.yml
These configurations are not used by default, and require small changes to the configuration files to use them. See comments included in the configs for more details.
=> Add tail sampling configuration for Grafana Agent and OTel Collector.

k8s/mythical/mythical-beasts-deployment.yaml
On code update, this will be re-instated. These manifests work correctly and have been tested wth reference to the GET docs.
=> Updated the k8s manifest to remove server readiness probe.

source/mythical-beasts-requester/index.js, tempo/tempo.yaml
Two changes. I forgive you for refusing the spiky graphs one.
The first creates some spikiness in the graphs which can provide for more interesting data to view.
The second forces the local blocks processor to store all spans which makes traceql metrics accurate.
Technically traceql metrics won't work until Grafana 10.4 and Tempo 2.4 but this will set things up for when the code catches up.
=> Spiky graphs and local blocks config

docker-compose-otel.yml, docker-compose.yml, grafana/definitions/traces-in-dashboards.json, tempo/tempo.yaml
PR #73 unfortunately included changes that should
not have been committed, including building from
source and an incorrect Tempo config.
This rectifies this and ensures that the images
and dashboards now work again correctly.
=> Fixes issues occuring from PR #73.

source/mythical-beasts-requester/index.js, source/mythical-beasts-server/index.js
Changes to allow intro-to-mltp to be used to generate local data during tracing app development. We would like to run two sets of the requester/server combo. One that is failing in cluster "A" and one succeeding in cluster "B". These changes will allow us to locally run the desired setup.
=> Add configurable errors and mythical server

grafana/definitions/mlt.json, source/mythical-beasts-requester/index.js
Update `mythical-beasts-requester/index.js` to Prefix Endpoint with a `/`, so that Trace Metrics have a consistent `http.target` value.
Currently some are `/beast` and others are `beast`, which gives conflicting results.
Example;
For Mythical Server;
I don't believe this has a wider impact to the Traces or Metrics produced, but this may need verifying.
This may need some discussion to understand whats expected and similar, or if there is an intentional reason for this.
=> Update `mythical-beasts-requester/index.js` to Prefix Endpoint with a `/`

cloud/dashboard-metrics-logs-traces-1.json
The panel "**Autologged Errors**" expression for Loki mismatch the configured *job_name* in *config.alloy*
Matching correction : 
> config.alloy (l.75)
```
job_name = "alloy"
```
> cloud/dashboard-metrics-logs-traces-1.json (l.807)
```
"expr": "{job=\"alloy\"} | logfmt | status=\"Error\""
```
=> Fix Loki expr in Dashboard to match job "alloy"

README.md, alloy/config.alloy, docker-compose-cloud.yml, docker-compose-otel.yml, docker-compose.yml, source/mythical-beasts-requester/index.js
Also:
* Updates README to correct links.
* Adds a Loki processor to the Alloy config to use timestamps in loglines from mythical-requester.
* Adds a TIMESHIFT envvar to the Docker Compose manifest for mythical-requester, which allows the time for a log entry to be 40 minutes in the past (shows off above Alloy processor functionality).
=> Updates to latest version of Grafana components.

.github/workflows/publish-and-deploy-images.yaml, .github/workflows/pull-request-build-images.yaml, .github/workflows/release-version.yaml
* Builds on PR for image testing, with branch tags.
* Builds on PR merge with `latest` and `main` tags.
* Builds with version publishing to allow versioned tags.
Been meaning to do this for ages, and recent rebuild woes have forced my hand.
=> Add workflows for auto-building and releasing the application images.

README.md
There was a typo in mimir/mimir.yaml refference (maybe file was renamed)
=> Fixed typo in mimir/mimir.yaml refference

.github/dependabot.yml
Adds a Dependabot Configuration to create PRs to Bump Package Dependencies for Docker and NPM, and also Workflow Actions.
Once enabled, and initial PRs generated and merged, it would be good to trigger a (Minor) release if possible.
=> [chore] - Add Dependabot Configuration to Create PRs for Dependency Updates

source/mythical-beasts-server/index.js
This PR allows you to specify the Mythical Database Connection Details and Credentials via Environment Variables.
This allows you to set a custom Hostname, or Password for the Database Connection.
=> Allow specifying Mythical Database Connection Details and Credentials via Environment Variables

source/mythical-beasts-server/index.js
Allow specifying a Custom Value to use for the Database Full Teardown Timeout, this is to allow for more frequent teardowns for some use cases.
=> Allow specifying a Custom Value to use for the Database Full Teardown Timeout

alloy/config.alloy, docker-compose-cloud.yml, docker-compose-otel.yml, docker-compose.yml, otel/otel.yml
Adds an OTLP HTTP endpoint to both Alloy and the
OpenTelemetry Collector, and includes changes to both configurations to output metrics in Prometheus format.
=> Add OTLP HTTP receiver and OTLP metrics pipeline.

source/mythical-beasts-recorder/index.js, source/mythical-beasts-requester/index.js, source/mythical-beasts-server/index.js
This PR adds a `namespace` Tag, to all Profiles from the Mythical Services (Recorder, Requester and Server) to set the Value to the Namespace Value from the Environment Variable (already defined and used elsewhere) and fallsback to `mythical` if its not set.
=> feat: Add Namespace Label/Tag to Profiles in Mythical Services

.github/workflows/publish-and-deploy-images.yaml, README.md, alloy/config.alloy, docker-compose.yml, source/mythical-beasts-frontend/.gitignore, source/mythical-beasts-frontend/Dockerfile, source/mythical-beasts-frontend/nginx.conf, source/mythical-beasts-frontend/package-lock.json, source/mythical-beasts-frontend/package.json, source/mythical-beasts-frontend/public/index.html, source/mythical-beasts-frontend/public/manifest.json, source/mythical-beasts-frontend/rsbuild.config.js, source/mythical-beasts-frontend/src/App.css, source/mythical-beasts-frontend/src/App.js, source/mythical-beasts-frontend/src/components/BeastManager.css, source/mythical-beasts-frontend/src/components/BeastManager.js, source/mythical-beasts-frontend/src/faro.js, source/mythical-beasts-frontend/src/index.css, source/mythical-beasts-frontend/src/index.js, source/mythical-beasts-frontend/src/services/api.js, source/mythical-beasts-server/index.js, source/mythical-beasts-server/package-lock.json, source/mythical-beasts-server/package.json
This uses Faro to instrument telemetry from the
Browser app.
RSBuild for React. Things have changed a little
since the last time I wrote a frontend app!
=> Initial version of a frontend service.
